# Generated by Django 4.0.3 on 2022-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\HP\\OneDrive\\Desktop\\ZEN\\zen\\zen\\static\\assets\\images\\Logo.png'),
        ),
    ]
