# Generated by Django 4.0.3 on 2022-04-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_graph_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='image',
            field=models.ImageField(default='C:\\Users\\HP\\OneDrive\\Desktop\\ZEN\\zen\\zen\\static\\assets\\images\\Logo.png', upload_to=''),
        ),
    ]
