# Generated by Django 4.0.3 on 2022-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_graph_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
