# Generated by Django 4.0.3 on 2022-04-14 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_graph_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='graph',
        ),
    ]
